# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Hero block with heading, text & a colored button.
  icon: 'cottage'
  tags: ['block', 'hero']

# Defines the structure of this component, as well as the default values
blueprint:
  bg_image:
  heading:
  text:
  button: bookshop:global/button

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
