# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Image carousel"
  description: An infinite looping image carousel
  icon: collections
  tags: ['image', 'carousel', 'slider']

# Defines the structure of this component, as well as the default values
blueprint:
  bg_image: 
  with_heading: false
  images: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:      
  images:
    type: array
  images[*]:
    type: image