# Metadata about this component, to be used in the CMS
spec:
  structures:
    - buttons
  label: Secondary Button
  description: Button with outline
  icon: 'smart_button'
  tags:
    - Button
    - Outline

# Defines the structure of this component, as well as the default values
blueprint:
  button_text: Button Text
  button_icon:
  button_link: ''
  text_color: '#034ad8'
  hover_brightness: 0.85

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
