# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Left-Right Block
  description: Left-Right block with heading, text & button next to image.
  icon: 'chrome_reader_mode'
  tags: ['block', 'left-right']

# Defines the structure of this component, as well as the default values
blueprint:
  image_on_left: false
  heading_text: bookshop:heading-text!
  bg_image:
  image:
  image_alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading_text:
    _bookshop_name: heading-text
    heading_level: h1
    heading: Test
    text: Something?

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:

