# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Master slider"
  description: This is a base component that extends card-slider and image-slider - the user should not see this directly
  icon: view_carousel
  tags: [ 'slider' ]

# Defines the structure of this component, as well as the default values
blueprint:  

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:  