# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Image carousel"
  description: An infinite looping image carousel
  icon: view_carousel
  tags: ['image', 'carousel', 'slider']

# Defines the structure of this component, as well as the default values
blueprint:
  heading_text: bookshop:heading-text
  card_border_radius: 4
  slides: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:  
  heading_text:
    comment: Add a block to the top of this slider with optional heading, text and button.
  card_border_radius:
    comment: How rounded do you want your image corners (in %)?
    type: range
    options:
      step: 1
      min: 0
      max: 50 
  slides:
    type: array
  slides[*]:
    type: image