# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Card carousel"
  description: An infinite looping card carousel
  icon: collections
  tags: ['card', 'carousel', 'slider']

# Defines the structure of this component, as well as the default values
blueprint:
  with_heading: false
  card_border_radius: 4
  image_border_radius: 50
  slides: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:      
  slides:
    type: array
  slides[*]:
    heading: This is a heading
    image: /images/carousel/carousel-01.jpg