# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Image"
  description: An image that will be optimised
  icon: image
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image_path:
  alt_text:
  image_sizes:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image_path: /assets/images/blog/featured-image-1.jpg
  alt_text: A child sitting at a desk
  image_sizes: 100vw

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image_sizes:
    hidden: true
