# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Editor Note"
  description: This should be used for a developer to convey a message to an editor
  icon: info
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: 
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent orci est, rhoncus ac facilisis id, ornare non nunc. Proin vehicula pretium blandit. Phasellus id est molestie

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
